name: Deploy to VPS

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Clean up previous 
        run: |
          sudo -n pm2 stop platform-azoozgat || true
          sudo -n pm2 delete platform-azoozgat || true
          sudo -n rm -rf /actions-runner/_work/AzoozGAT-Platform/AzoozGAT-Platform/.next

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          clean: true

      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci --force
      
      - name: Create environment file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env.local
        
      - name: Clean Next.js cache and build
        run: |
          npm run build

      - name: Setup PM2 
        run: |
          sudo -n npm install -g pm2
          sudo -n pm2 stop platform-azoozgat || true
          sudo -n pm2 delete platform-azoozgat || true
          sudo -n NODE_ENV=production pm2 start npm --name "platform-azoozgat" --cwd "/actions-runner/_work/AzoozGAT-Platform/AzoozGAT-Platform" -- start
          sudo -n pm2 save
          sudo -n pm2 startup

      - name: Install Caddy if not already installed
        run: |
          if ! command -v caddy &> /dev/null; then
            sudo -n apt update
            sudo -n apt install -y debian-keyring debian-archive-keyring apt-transport-https
            curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo -n gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
            curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo -n tee /etc/apt/sources.list.d/caddy-stable.list
            sudo -n apt update
            sudo -n apt install -y caddy
          fi

      - name: Configure Caddy
        run: |
          sudo -n systemctl stop caddy || true
          
          # Create Caddy configuration file
          sudo -n tee /etc/caddy/Caddyfile > /dev/null <<EOF
          azoozgat.com {
            reverse_proxy localhost:3000
          }
          EOF
          sudo -n systemctl start caddy
          
      - name: Verify deployment
        run: |
          # Check Caddy status
          sudo -n systemctl status caddy || true
          
          # Check PM2 status
          sudo -n pm2 status || true
          
          # Verify app is responding
          curl -I http://localhost:3000 || true
          
          echo "Deployment complete. Site should be available at https://azoozgat.com"