name: Deploy to VPS

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci --force
      
      - name: Create environment file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env.local
        
      - name: Build application
        run: npm run build
      
      - name: Setup PM2
        run: |
          sudo -n npm install -g pm2
          pm2 stop platform-azoozgat || true
          pm2 delete platform-azoozgat || true
          NODE_ENV=production pm2 start npm --name "platform-azoozgat" --cwd "/actions-runner/_work/AzoozGAT-Platform/AzoozGAT-Platform" -- start
          pm2 save
          sudo env PATH=$PATH:/usr/bin pm2 startup systemd -u root --hp $HOME || true
      
      - name: Configure Nginx
        run: |
          sudo -n cp ./nginx/platform-azoozgat.conf /etc/nginx/sites-available/platform-azoozgat
          sudo -n ln -sf /etc/nginx/sites-available/platform-azoozgat /etc/nginx/sites-enabled/
          sudo -n nginx -t && sudo -n systemctl reload nginx