name: Deploy to VPS

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Thorough Cleanup
        run: |
          # Stop the application first to release any file locks
          pm2 stop platform-azoozgat || true
          
          # Clean up build artifacts and dependencies
          sudo -n rm -rf /actions-runner/_work/AzoozGAT-Platform/AzoozGAT-Platform/.next/ || true
          sudo -n rm -rf /actions-runner/_work/AzoozGAT-Platform/AzoozGAT-Platform/node_modules/ || true
          sudo -n rm -rf /actions-runner/_work/AzoozGAT-Platform/AzoozGAT-Platform/.cache/ || true
          
          # Clean browser caches by adding a timestamp file that will force reload
          mkdir -p /actions-runner/_work/AzoozGAT-Platform/AzoozGAT-Platform/public/version
          date > /actions-runner/_work/AzoozGAT-Platform/AzoozGAT-Platform/public/version/timestamp.txt
      
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          clean: true
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci --force
      
      - name: Create environment file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env.local
        
      - name: Clean Next.js cache and build
        run: |
          rm -rf .next
          npm run build
      
      - name: Setup PM2
        run: |
          sudo -n npm install -g pm2
          pm2 stop platform-azoozgat || true
          pm2 delete platform-azoozgat || true
          
          # Set proper permissions for the .next directory
          chmod -R 755 .next
          
          # Start with production mode
          NODE_ENV=production pm2 start npm --name "platform-azoozgat" --cwd "/actions-runner/_work/AzoozGAT-Platform/AzoozGAT-Platform" -- start
          pm2 save
          sudo env PATH=$PATH:/usr/bin pm2 startup systemd -u root --hp $HOME || true
      
      - name: Configure Nginx
        run: |
          sudo -n cp ./nginx/platform-azoozgat.conf /etc/nginx/sites-available/platform-azoozgat
          sudo -n ln -sf /etc/nginx/sites-available/platform-azoozgat /etc/nginx/sites-enabled/
          sudo -n nginx -t && sudo -n systemctl reload nginx
          
      - name: Clear Nginx cache
        run: |
          sudo -n rm -rf /var/cache/nginx/* || true
          sudo -n systemctl reload nginx